steps:
  # Build App Image - Step #12
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '--build-arg', 'BUILD_VERSION=${_APP_VERSION}', '-t', 'us.gcr.io/nexus-284522/qr-app:dev-${_APP_VERSION}-${SHORT_SHA}', '-t', 'us.gcr.io/nexus-284522/qr-app:latest', '.']
    id: "QR_BUILD_APP"
    waitFor: ['-']

images:
  - 'us.gcr.io/nexus-284522/qr-app:dev-${_APP_VERSION}-${SHORT_SHA}'
  - 'us.gcr.io/nexus-284522/qr-app:latest'

substitutions:
  _APP_VERSION: 1.0.0
 
# options:
#   workerPool: 'odsp-management/cloud-build-workers'
